[Cthulhu]
asm_syntax = "att"
dead_code_elimination = true
debuginfo = "compact"
enable_highlighter = true
highlighter = ["pygmentize", "-l"]
inline_cost = false
iswarn = false
optimize = true
pretty_ast = false
remarks = false
type_annotations = true
with_effects = false
