name: Performance Regressions
on: [push, pull_request]
jobs:
  build-and-benchmark:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1']
        julia-arch: [x64]
        os: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Julia
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
    - name: Build project
      - uses: julia-actions/julia-buildpkg@latest
    - run: julia -e '
            using Pkg;
            Pkg.add(["Test", "TestSetExtensions"]);
            Pkg.add(url="https://github.com/sumiya11/Groebner.jl");
            include("test/runtests.jl")'
